version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=wp_db_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wp_db
    volumes:
      - dbfile:/var/lib/mysql
    networks:
      - app

  wp:
    image: wordpress:5.7.0-php8.0-fpm
    container_name: wordpress-phpfpm
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wp_db_user
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wp_db
    volumes:
      - www-html:/var/www/html
    networks:
      - app

  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - wp
    container_name: nginx-1.19.8-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - www-html:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app

volumes:
  www-html:
  dbfile:
  nginx:

networks:
  app:
    driver: bridge
